/**
 * API Configuration (auto-generated from root appConfig.js)
 * Do not edit this file directly. Edit appConfig.js in the project root and run: node scripts/sync-config.js
 */
// live server
const API_BASE_URL = "http://93.127.129.102:3941/api";
const BACKEND_URL = "http://93.127.129.102:3941";

// testbed
// const API_BASE_URL = "http://93.127.129.102:3940/api";
// const BACKEND_URL = "http://93.127.129.102:3940";

export { API_BASE_URL, BACKEND_URL };
